
#ifndef EXTERNAL_INT_CFG_H_
#define EXTERNAL_INT_CFG_H_

#define		Global_INT					GLOBAL_INT_EN
#define		EXTERNAL_INT0_TRIGGER		INT0_TRIGGER_RISING_EDGE
#define		EXTERNAL_INT1_TRIGGER		INT1_TRIGGER_RISING_EDGE
#define		EXTERNAL_INT2_TRIGGER		INT2_TRIGGER_FALLING_EDGE


#endif /* EXTERNAL_INT_CFG_H_ */