
#include "EXternal_INT.h"

void SET_GlobalINTS(void)
{
	#if		Global_INT==GLOBAL_INT_EN
	
	SET_BIT(SREG,7);
	
	#elif	Global_INT==GLOBAL_INT_DS
	
	CLR_BIT(SREG,7); 
	
    #endif
}
void ExternalINT0_Init(void)
{
	SET_GlobalINTS();
	SET_BIT(GICR,EXTERNAL_INT0);
	
	#if		EXTERNAL_INT0_TRIGGER==INT0_TRIGGER_LOW_LEVEL
	
	CLR_BIT(MCUCR,0); 
	CLR_BIT(MCUCR,1); 
	
	#elif	EXTERNAL_INT0_TRIGGER==INT0_TRIGGER_RISING_EDGE
	
	SET_BIT(MCUCR,0); 
	CLR_BIT(MCUCR,1);
	
	#elif	EXTERNAL_INT0_TRIGGER==INT0_TRIGGER_FALLING_EDGE
	
	CLR_BIT(MCUCR,0);
	SET_BIT(MCUCR,1);
	
	#elif	EXTERNAL_INT0_TRIGGER==INT0_TRIGGER_ANY_LOGICAL_CHANGE
	
	SET_BIT(MCUCR,0);
	SET_BIT(MCUCR,1);
	
	#endif
	
	
	
}
void ExternalINT1_Init(void)
{
	SET_GlobalINTS();
	SET_BIT(GICR,EXTERNAL_INT1);
	
	#if		EXTERNAL_INT1_TRIGGER==INT1_TRIGGER_LOW_LEVEL
	
	CLR_BIT(MCUCR,2);
	CLR_BIT(MCUCR,3);
	
	#elif	EXTERNAL_INT1_TRIGGER==INT1_TRIGGER_RISING_EDGE
	
	SET_BIT(MCUCR,2);
	CLR_BIT(MCUCR,3);
	
	#elif	EXTERNAL_INT1_TRIGGER==INT1_TRIGGER_FALLING_EDGE
	
	CLR_BIT(MCUCR,2);
	SET_BIT(MCUCR,3);
	
	#elif	EXTERNAL_INT1_TRIGGER==INT1_TRIGGER_ANY_LOGICAL_CHANGE
	
	SET_BIT(MCUCR,2);
	SET_BIT(MCUCR,3);
	
	#endif
}
void ExternalINT2_Init(void)
{
	SET_GlobalINTS();
	SET_BIT(GICR,EXTERNAL_INT2);
	#if	EXTERNAL_INT2_TRIGGER==INT2_TRIGGER_RISING_EDGE
	
	SET_BIT(MCUCSR,6);
	
	#elif	EXTERNAL_INT2_TRIGGER==INT2_TRIGGER_FALLING_EDGE
	
	CLR_BIT(MCUCSR,6);
	
	#endif
}
